host-IT-Project/frontend

src/App.jsx
src/components/Header.jsx
src/components/SearchFilter.jsx

Issue: https://github.com/host-IT-Project/frontend/issues/2

추가: Header, SearchFilter 컴포넌트 생성

---

src/components/Header.jsx

로고(호잇) 클릭시 HomePage로 이동하도록 기능을 추가하였습니다.

추가: 로고 클릭시 HomePage로 이동

---

package-lock.json
package.json
src/api/APITest.jsx
src/api/article.js
src/api/http.js
src/components/ProductCardList.jsx
src/components/search/OptionSearch.jsx
src/components/search/SearchForm.jsx
src/pages/ArchivePage.jsx
src/pages/HomePage.jsx
src/template/PageTemplate.jsx
src/util/type.js

https://user-images.githubusercontent.com/87746574/194740327-2c26249f-2339-4d58-af19-e9251d258c09.mov
https://mui.com/material-ui/react-autocomplete/#search-input
- 전체 게시물 수가 많지 않으므로 검색 결과가 존재하지 않는다는 화면이 자주 나타날 경우 사용자 경험을 저하시킬 수 있음. 따라서 검색 결과가 존재하지 않는 경우에는 "'검색어ABC'와(과) 일치하는 검색결과가 없습니다. 아래의 게시물들은 어떠신가요?"라는 문구와 함께 전체 게시물을 출력함
-

추가: 검색 기능 구현

---

package-lock.json
package.json
src/api/APITest.jsx
src/api/article.js
src/api/http.js
src/pages/HomePage.jsx
src/util/type.js

Issue: #15 
- https://jsdoc.app/tags-param.html
```
/**
*
* @TODO
* Array와 Object 타입을 확인할 수 있는 코드가 필요합니다.
*/
export const checkType = (value, type) => {
...
};
```
```
/**
* @TODO
* baseURL 숨김 처리
*/
const axios = Axios.create({
baseURL: 'https://31970935-739c-4289-9eda-04fb30cc0da0.mock.pstmn.io/',
});
```

#15 - 추가: axios를 사용한 API 호출 구현

---

package-lock.json
package.json
src/components/ProjectInfoBox.jsx
src/components/TextEditor.jsx
src/components/TextViewer.jsx
src/pages/ProjectDetailPage.jsx
src/pages/Routes.jsx

Issue: #12 
프로젝트 상세페이지 UI를 작업했습니다.
- 현재 API 작업중이라고 해서 더미데이터를 사용하고 있어 추후 수정이 필요합니다.
- 디자인 detail이 어긋나는 부분은 Main 브랜치 병합 후 수정하겠습니다.
- 자신의 글만 수정할 수 있도록 사용자 확인하는 부분이 필요합니다. 로그인하지 않은 상태에서 수정을 누르면 로그인 화면으로 이동해야합니다.
- 썸네일 url을 가져오는 것도 작업해야합니다

추가: ProjectDetailPage UI 작업

---

src/api/APITest.jsx
src/api/article.js

issue: #33 
- article의 ID를 파라미터로 받으면 해당 id를 가진 article을 넘겨주는 getArticle API를 만들었습니다.
- 기존의 delete, post API와 http의 get을 참고해 작성했습니다.

추가: getArticle API 추가

---

src/components/ProjectInfoBox.jsx
src/pages/ProjectDetailPage.jsx

Issue: #33
- #34 getArticle을 활용해 데이터를 넘겨받도록 작품 상세페이지를 수정하였습니다.

추가: 작품 상세페이지 url parm에 따라 article 데이터 불러오기

---

src/pages/ProjectDetailPage.jsx

작품상세페이지에서 `Uncaught TypeError: Cannot read properties of undefined` 에러가 뜨며 화면이 렌더링되지 않는 문제를 해결하였습니다.

수정: 작품 상세페이지 비동기 article 정보 조건부 렌더링 처리

---

public/index.html
src/App.css
src/components/EditForm.jsx
src/components/EditFormValidator.js
src/components/TagInput.jsx
src/styles/theme.js

추가: EditPage UI, 유효성검사 및 썸네일이미지 이미지 스토리지 저장 기능 구현

---

src/components/MoreMenu.jsx
src/components/ProductCardHoriz.jsx
src/components/TagArray.jsx
src/pages/MyPage.jsx

- ProductCardHoriz
- MoreMenu
컴포넌트를 작업했습니다
수정, 삭제 기능이 있는 더보기 메뉴입니다.
삭제를 누르면 Delete API 호출합니다.
수정을 누르면 "/edit?id={id}"로 이동합니다.

추가: 마이페이지 가로형 카드 컴포넌트 생성

---

src/components/ProductCardHoriz.jsx
src/components/ProductCardList.jsx
src/pages/MyPage.jsx

- 마이페이지의 CardList를 구현했습니다.
- 만약 아티클 리스트를 받아왔는데 길이가 0이라면 "아직 등록된 게시물이 없습니다" 문구가 출력됩니다.

추가: 마이페이지 UI 구성 및 사용자 아티클 받아오기

---

src/components/ProjectInfoBox.jsx
src/pages/ProjectDetailPage.jsx

추가: 작성자가 아닌 유저가 상세페이지에 접근 시 수정버튼 숨김

---

src/atom/articleAtom.js
src/components/NewArticleButton.jsx
src/pages/EditPage.jsx
src/template/PageTemplate.jsx

- 새 글 쓰기 버튼을 누를 시 Edit 페이지로 이동합니다
- EditPage, LoginPage 등을 제외한 페이지의 우측 하단에 버튼이 고정되어있습니다.

추가: 새 글 쓰기 버튼 컴포넌트 생성 및 페이지 템플릿에 부착

---

src/api/APITest.jsx
src/api/article.js
src/api/http.js
src/components/ProductCardHoriz.jsx
src/components/ProjectInfoBox.jsx
src/pages/MyPage.jsx

- 수정된 article 데이터 구조에 맞춰 API를 수정했습니다.
```js
/**
*
* @param {string} title
* @param {string} description
* @param {string} content
* @param {Array<string>} [hashtagList]
* @param {string} thumbnail
*/
export const postArticle = ({
title,
description,
content,
hashtagList,
thumbnail,
} = {}) => {
title && checkType(title, "string");
description && checkType(description, "string");
content && checkType(content, "string");
hashtagList && checkType(hashtagList, "object");
thumbnail && checkType(thumbnail, "string");
return http
.post(`/api/board/1/articles`, {
title,
description,
content,
hashtagList,
thumbnail,
})
.catch((error) => {
console.log(error.response.data);
console.log(error.response.status);
console.log(error.response.headers);
window.alert("게시물 등록에 실패했습니다.");
});
};
```
```js
/** …
```

수정: CRUD API 수정

---

src/App.jsx
src/pages/LoginPage.jsx

https://github.com/host-IT-Project/frontend/pull/50#issue-1456986089
게시물 삭제, 마이페이지 새로고침 시 발생하던 LoginPage redirection 현상을 수정했습니다.

LoginPage redirection 수정

---

package-lock.json
package.json
src/components/Spinner.jsx
src/components/login/RedirectLogin.jsx
src/pages/LogoutPage.jsx
src/pages/MyPage.jsx
src/pages/ProjectDetailPage.jsx

Spinner 컴포넌트 생성 및 각 페이지에 추가

---

src/api/APITest.jsx
src/api/user.js

- 내 정보 가져오기`/api/user-info`로 요청
- 내 게시물 가져오기`/api/article/users-article`로 요청

User 정보 가져오기, 내 게시글 가져오기 모듈 작성

---

src/components/ProductCardList.jsx
src/pages/MyPage.jsx

추가: 마이페이지에서 내 게시글 불러오기

---

src/components/ProductCard.jsx

메인페이지 카드 제목 말줄임 처리

---

src/pages/HomePage.jsx

메인페이지 카드리스트 가로스크롤바

---

src/components/NewArticleButton.jsx
src/pages/EditPage.jsx
src/util/uploadLimit.js

추가: 11월 23일 11시 이후 글 수정/등록 불가

---

src/components/TagInput.jsx

수정: 해시태그 15자까지

---

src/App.jsx
src/components/NewArticleButton.jsx
src/pages/EditPage.jsx

수정: 새 글 등록 오류 수정

---

src/pages/EditPage.jsx

- 게시글 수정이 가능하도록 기능 오픈
- 수정 모드로 edit 페이지에 접근했을 때 시간제한 함수를 호출하지 않도록 변경

수정: 글 수정기능 제한 해제

---

src/api/APITest.jsx

API Test 테스트 코드 수정
